### ISSUE TITLE
Failed to activate the set-syntax package

### ISSUE THREAD

**Issue by nexli** [lee-dohm/set-syntax#13]
Error: Arguments to CompositeDisposable.add must have a .dispose() method

Trace:
TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (C:\Users\master\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (C:\Users\master\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:43:11)
    at file:///C:/Users/master/.atom/packages/set-syntax/lib/main.coffee:11:20
    at Array.map (native)
    at Object.module.exports.activate (file:///C:/Users/master/.atom/packages/set-syntax/lib/main.coffee:10:33)
    at Package.module.exports.Package.activateNow (C:\Users\master\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:183:20)
    at C:\Users\master\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\master\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:92:15)
    at C:\Users\master\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\master\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\master\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\master\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:397:31
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by lee-dohm** [comment]
The next time you get this error, can you include the full output from the unhandled exception dialog? There is a lot of diagnostic information in there that would be helpful.

**Comment by mmagnuski** [comment]
I got this error too.

**Atom**: 1.23.3 ia32
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [set-syntax](https://github.com/lee-dohm/set-syntax) package 0.3.0


### Stack Trace

Failed to activate the set-syntax package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/composite-disposable.js:74:19)
    at CompositeDisposable.module.exports.CompositeDisposable.add (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/composite-disposable.js:43:17)
    at /packages/set-syntax/lib/main.coffee:11:20
    at Array.map (native)
    at Object.activate (/packages/set-syntax/lib/main.coffee:10:33)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:255:25)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.23.3/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.23.3/resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.23.3/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.23.3/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.23.3/resources/app/src/package-manager.js:647:50)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/src/atom-environment.js:865:36
```

### Commands

```
```

### Non-Core Packages

```
Hydrogen 1.7.0 
ink 0.6.5 
julia-client 0.5.12 
language-julia 0.11.0 
language-matlab 0.2.1 
language-matlab-octave 0.1.2 
latex-completions 0.3.2 
linter-matlab 1.1.0 
set-syntax 0.3.0 
tabs-to-spaces 1.0.3 
tool-bar 1.0.1 
uber-juno 0.1.1 
vim-mode-plus 0.92.1 
```

**Comment by lee-dohm** [comment]
@mmagnuski Please install the latest version of the package.

**Comment by mmagnuski** [comment]
sure! :)
